apiVersion: v1
kind: Service
metadata:
  name: example-website
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
    site: example-website
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-website
  labels:
    app: wordpress
    site: example-website
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
        site: example-website
    spec:
      containers:
        - image: ripeworks/wordpress:0.5
          name: wordpress
          ports:
            - containerPort: 80
          volumeMounts:
            - name: efs
              mountPath: /app
      volumes:
        - name: efs
          nfs:
            server: fs-92b64dda.efs.us-east-1.amazonaws.com
            path: /wordpress/my-website.com

