apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
--
apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - image: ripeworks/wordpress:latest
          name: wordpress
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: efs
              mountPath: /app
          volumes:
            - name: efs
              nfs:
                server: fs-92b64dda.efs.us-east-1.amazonaws.com
                path: /wordpress/mywebsite.com

