apiVersion: v1
kind: Service
metadata:
  name: wordpress-versicor
  labels:
    app: wordpress
    site: versicor
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    site: versicor
  type: LoadBalancer
--
apiVersion: v1
kind: Deployment
metadata:
  name: wordpress-versicor
  labels:
    app: wordpress
    site: versicor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        site: versicor
    spec:
      containers:
        - image: ripeworks/wordpress:latest
          name: wordpress
          ports:
            - containerPort: 80
          volumeMounts:
            - name: efs
              mountPath: /app
          volumes:
            - name: efs
              nfs:
                server: fs-92b64dda.efs.us-east-1.amazonaws.com
                path: /wordpress/goversicor.com

